### create admin
POST http://localhost:3000/auth/admin/signup
Content-Type: application/json

{
  "name": "james",
  "password": "shunn",
  "employee_id": "shunnnn",
  "role_id": "admin"
}

### create others
POST http://localhost:3000/auth/signup
Content-Type: application/json
Set-Cookie: refresh-token=IKYGAxr4NuGmAlgX90GEvbnYn; HttpOnly
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImFkbWluIiwiZW1wbG95ZWVfcm9sZSI6ImFkbWluIiwiaXNzIjoiR28gUmVzdGF1cmVudCIsInN1YiI6Imp3dCIsImF1ZCI6WyJhZG1pbiIsInVzZXIiXSwiZXhwIjoxNzIyODQwMTQ1LCJpYXQiOjE3MjI4NDAwODV9.twDGRkqZ3On6WDadBgLMwGTgFfwHrvZscYFvCyLgYos

{
  "name": "shunn1",
  "password": "shunn1",
  "employee_id": "shunnleyee1",
  "role_id": "manager"
}

### admin login
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "employee_id": "admin",
  "password": "admin"
}

### manager login
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "employee_id": "shunnleyee",
  "password": "shunn"
}


### refresh token
GET http://localhost:3000/auth/refresh
Set-Cookie: refresh-token=HMGzBajAVF3x8G5FahOzSIVQU; HttpOnly
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImFkbWluIiwiZW1wbG95ZWVfcm9sZSI6ImFkbWluIiwiaXNzIjoiR28gUmVzdGF1cmVudCIsInN1YiI6Imp3dCIsImF1ZCI6WyJhZG1pbiIsInVzZXIiXSwiZXhwIjoxNzIyODQxNjQ0LCJpYXQiOjE3MjI4NDE1ODR9.Wz9RWxAilpBD3pCQFZp0OOXUH2G3N6F-TRpUkImdt7I

