POST http://localhost:3000/roles
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6InNodW5ubGV5ZWUiLCJlbXBsb3llZV9yb2xlIjoibWFuYWdlciIsImlzcyI6IkdvIFJlc3RhdXJlbnQiLCJzdWIiOiJqd3QiLCJhdWQiOlsiYWRtaW4iLCJ1c2VyIl0sImV4cCI6MTcyMjgzNjM0OCwiaWF0IjoxNzIyNzQ5OTQ4fQ.pu82Ngbm78ktjZTVYNM7vIJeL-otML63LA-xjPvOlyI

{
  "role_id": "manager"
}