// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type MenuCategory struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	ImgUrl    string       `json:"img_url"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type MenuItem struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Price       float32       `json:"price"`
	Description string        `json:"description"`
	Ingredients string        `json:"ingredients"`
	ImgUrl      string        `json:"img_url"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
	Category    uuid.NullUUID `json:"category"`
	SubCategory uuid.NullUUID `json:"sub_category"`
}

type MenuSubCategory struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	ImgUrl    string       `json:"img_url"`
	Category  uuid.UUID    `json:"category"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}
