// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type MenuCategory struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	ImgUrl    string       `json:"img_url"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type MenuItem struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Price       float32       `json:"price"`
	Description string        `json:"description"`
	Ingredients string        `json:"ingredients"`
	ImgUrl      string        `json:"img_url"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
	Category    uuid.NullUUID `json:"category"`
	SubCategory uuid.NullUUID `json:"sub_category"`
}

type MenuSubCategory struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	ImgUrl    string       `json:"img_url"`
	Category  uuid.UUID    `json:"category"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Permission struct {
	ID         int32        `json:"id"`
	Permission string       `json:"permission"`
	Method     string       `json:"method"`
	Route      string       `json:"route"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

type Role struct {
	ID        string       `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type RolePermission struct {
	ID         int32        `json:"id"`
	Role       string       `json:"role"`
	Permission string       `json:"permission"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID                uuid.UUID    `json:"id"`
	Name              string       `json:"name"`
	EncryptedPassword string       `json:"encrypted_password"`
	Role              string       `json:"role"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	EmployeeID        string       `json:"employee_id"`
}
